# -*- coding: utf-8 -*-
"""Преобразование из Мили в Мура.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kFtR2eMd8NEBK7TnxBTqMxnci26IjfVY
"""

import pandas as pd
from google.colab import files
import io
import csv

"""Загрузка файла с локального диска:"""

uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['inputNur.csv']))
df

"""Загрузка из google drive

```
# Описание
```


Войдите в аккаунт, в pd.read_csv() укажите ссылку к файлу
"""

from google.colab import drive
drive.mount('/content/gdrive')

df = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/operation_system/input.csv');
df

"""**Перевод из Мили в Мура:**"""

inputСharacters = []
for item in df['Unnamed: 0']:
  inputСharacters.append(item)

data = df.drop('Unnamed: 0', axis=1)
uniqueStates = []
for rowIndex, row in data.iterrows():
  for columnIndex, value in row.items():
    if (value not in uniqueStates):
      uniqueStates.append(value)

letter = 'q'
newStates = []
finishStates = []
index = 0
for item in uniqueStates:
  newStates.append(letter + str(index))
  finishStates.append(item.split('/'));
  index+=1

Y= []
Y.append('')
for item in finishStates:
  Y.append(item[1])

finish = []
array = []
array.append(newStates)
for index in range(0, len(inputСharacters)):
  finish.append(inputСharacters[index])
  for i in range(0, len(newStates)):
    column = df[finishStates[i][0]]
    ind = uniqueStates.index(column[index])
    finish.append(newStates[ind])
  array.append(finish)
  finish =[]
array[0].insert(0, '')

outputFile = 'output.csv'
result = pd.DataFrame(array, columns=[Y])
print(result)
f2 = open(outputFile, 'w')
result.to_csv(f2, index=False)
files.view(outputFile)

"""Скачать файл в csv формате:"""

files.download(outputFile);

"""Перевод из Мура в Мили"""

data = pd.DataFrame()
columns = []
for col in df.columns:
  col = str(col).replace("'", "", 2)
  col = str(col).replace("(", "")
  col = str(col).replace(")", "")
  col = str(col).replace(",", "")
  columns.append(col)

for i in range(0, len(df.index)):
  for j in range(0, len(columns)):
    if i != 0 and j != 0:
      data.at[i, j] = df.iat[i, j] + '/' + columns[j]
    else:
      data.at[i, j] = df.iat[i, j]

columnNames = data.iloc[0]
data.drop(0, axis=0, inplace=True)
data.columns = columnNames

outputFile = 'output.csv'
data
f2 = open(outputFile, 'w')
data.to_csv(f2, index=False)
files.view(outputFile)

"""Скачать файл в csv формате:"""

files.download(outputFile);